matrix:
  include:
    - name: Ubuntu 20.04 Clang
      os: linux
      dist: focal
      env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
      - FILE_SUF="clang"
      addons:
        apt:
          packages:
          - cmake
          - make
          - libsdl2-dev
          - libogg-dev
          - libvorbis-dev
          - libopenal-dev
          - libalut-dev
          - libfreetype6-dev
          - libfontconfig1-dev
    - name: Ubuntu 20.04 GCC
      os: linux
      dist: focal
      env:
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - FILE_SUF="gcc"
      addons:
        apt:
          packages:
          - cmake
          - make
          - libsdl2-dev
          - libogg-dev
          - libvorbis-dev
          - libopenal-dev
          - libalut-dev
          - libfreetype6-dev
          - libfontconfig1-dev
    - name: Ubuntu 20.04 MinGW
      os: linux
      dist: focal
      env: MINGW="true"
      addons:
        apt:
          packages:
          - cmake
          - make
          - p7zip-full
          - mingw-w64
          - wine
          - wine32
    - name: macOS native compilation
      os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
          - sdl2
          - libogg
          - libvorbis
          - freealut
          - freetype

language: cpp

git:
  depth: false

branches:
  only:
  - master

env:
  global:
  - RELEASE_BRANCH=master

before_install:
  - eval "${MATRIX_EVAL}"
  - | 
      if [ "$MINGW" = "true" ]; then
        wget https://github.com/viewizard/astromenace-mingw-deps/releases/download/latest/deps.zip
        unzip -o deps.zip
        rm deps.zip
        export CUSTOM_CMAKE_ARGS="-DMINGW32=1 -DDEPS_PATH=$PWD/deps"
      fi

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../bin -DCMAKE_BUILD_TYPE=Release ${CUSTOM_CMAKE_ARGS}
  - cmake --build . --target install -- -j8
  - cd ..

before_deploy:
  - |
      if [ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        if [[ -z "$TRAVIS_TAG" ]]; then
          export TRAVIS_TAG="$(awk -F'"' '/GAME_VERSION/ {print $2}' ./src/build_config.h)-$(git rev-list HEAD --count)"
          git config --local user.name "Travis"
          git config --local user.email "travis@travis-ci.org"
          git tag "$TRAVIS_TAG" -a -m "[Autogenerated] This is the latest version pushed to the ${TRAVIS_BRANCH} branch."
          git push https://${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG} --tags >/dev/null 2>&1
        fi
        # Prepare files for deployment
        mv bin astromenace
        if [ "$MINGW" = "true" ]; then
          7z a astromenace-win.zip astromenace
        elif [ ${TRAVIS_OS_NAME} = 'linux' ]; then
          echo "Make sure, you have all required libs installed: libSDL2 (ver 2.0.5+), libopenal (ver 1.0+), libalut (ver 1.0+), libogg (ver 1.1+), libvorbis (ver 1.1+), freetype (ver 2.1.6+)." > ./astromenace/ReadMe.txt
          tar cfz astromenace-${TRAVIS_OS_NAME}-${FILE_SUF}-${TRAVIS_CPU_ARCH}.tar.gz ./astromenace/*
        elif [ ${TRAVIS_OS_NAME} = 'osx' ]; then
          echo "Make sure, you have all required libs installed with HomeBrew (https://brew.sh/): sdl2, libogg, libvorbis, freealut, freetype." > ./astromenace/ReadMe.txt
          tar cfz astromenace-${TRAVIS_OS_NAME}.tar.gz ./astromenace/*
        fi
      fi

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - "*.tar.gz"
    - "*.zip"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  name: "Autogenerated (for testing purposes only)"
  prerelease: true
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: $RELEASE_BRANCH

