language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
script:
  - cmake ./
  - make
  - ./astromenace --pack --rawdata=./gamedata
compiler:
  - clang
  - gcc
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install libegl1-mesa-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install cmake make libsdl2-dev libogg-dev libvorbis-dev libopenal-dev libalut-dev libfreetype6-dev libfontconfig1-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl2 libogg libvorbis freealut freetype; fi
notifications:
  email: true
