matrix:
  include:
    - os: linux
      dist: focal
      env: MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      dist: focal
      env: MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: osx
      osx_image: xcode12

language: cpp


before_install:
  - |
      eval "${MATRIX_EVAL}"
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get -qq install cmake make libsdl2-2.0-0 libsdl2-dev libogg-dev libvorbis-dev libopenal-dev libalut-dev libfreetype6-dev libfontconfig1-dev
      fi
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update
        brew upgrade
        brew install sdl2 libogg libvorbis freealut freetype
      fi

script:
  - cmake ./
  - make -j8

